# -*- coding: utf-8 -*-

# Target DocType
TARGET_DOCTYPE = "Dunning Letter"

# Setup Statuses
SETUP_STATUS_EDITING = "Editing"
SETUP_STATUS_FINALIZED = "Finalized"

# Block Types
BLOCK_TYPE_STATIC_TEXT = "Static Text"
BLOCK_TYPE_DYNAMIC_FIELD = "Dynamic Field"
BLOCK_TYPE_OCR_TEXT = "OCR Text"
BLOCK_TYPE_IMAGE = "Image"
BLOCK_TYPE_BRANDING = "Branding"

# Allowed Branding File Types
ALLOWED_BRANDING_EXTENSIONS = [".png", ".jpg", ".jpeg", ".svg"]
REJECTED_BRANDING_EXTENSIONS = [".webp", ".pdf"]

# Rate Limit Action Names
RATE_LIMIT_UPLOAD_PDF = "upload_pdf"
RATE_LIMIT_RUN_OCR = "run_ocr"
RATE_LIMIT_GENERATE_PREVIEW = "generate_preview"
RATE_LIMIT_SAVE_LAYOUT = "save_layout"
RATE_LIMIT_FINALIZE = "finalize"
RATE_LIMIT_GENERATE_OUTPUT = "generate_output"
RATE_LIMIT_RETURN_TO_EDITING = "return_to_editing"

# Stable Error Codes
ERROR_ACCESS_DENIED = "ACCESS_DENIED"
ERROR_GUEST_NOT_ALLOWED = "GUEST_NOT_ALLOWED"
ERROR_INVALID_TARGET_DOCTYPE = "INVALID_TARGET_DOCTYPE"
ERROR_SETUP_NOT_FOUND = "SETUP_NOT_FOUND"
ERROR_SETUP_FINALIZED = "SETUP_FINALIZED"
ERROR_INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
ERROR_PDF_TOO_LARGE = "PDF_TOO_LARGE"
ERROR_PDF_NOT_READABLE = "PDF_NOT_READABLE"
ERROR_PDF_PROTECTED = "PDF_PROTECTED"
ERROR_PDF_PAGE_COUNT_INVALID = "PDF_PAGE_COUNT_INVALID"
ERROR_OCR_NOT_CONFIGURED = "OCR_NOT_CONFIGURED"
ERROR_OCR_RATE_LIMITED = "OCR_RATE_LIMITED"
ERROR_OCR_PROVIDER_FAILED = "OCR_PROVIDER_FAILED"
ERROR_OUTPUT_UNSAFE = "OUTPUT_UNSAFE"
ERROR_RATE_LIMITED = "RATE_LIMITED"
